// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SV5T.Infrastructure.Persistence.Context;

#nullable disable

namespace SV5T.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SV5T.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AbsoluteExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsPersistent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUsedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AbsoluteExpiresAtUtc");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("FamilyId", "IsRevoked");

                    b.HasIndex("IsRevoked", "RevokedAtUtc");

                    b.HasIndex("UserId", "IsRevoked", "CreatedAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Campaigns.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AwardType")
                        .HasColumnType("int");

                    b.Property<string>("CollectiveEligibilityRuleJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid?>("PrerequisiteCampaignId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("RegCloseAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RegOpenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReviewDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("StandardSetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteCampaignId");

                    b.HasIndex("StandardSetId");

                    b.HasIndex("SchoolYear", "Level", "AwardType", "Status");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Criteria.Criterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("int");

                    b.Property<int?>("GroupCode")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumSatisfied")
                        .HasColumnType("int");

                    b.Property<int>("Operator")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentCriterionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReviewGuidance")
                        .HasColumnType("longtext");

                    b.Property<Guid>("StandardSetId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentCriterionId");

                    b.HasIndex("StandardSetId", "ParentCriterionId", "DisplayOrder");

                    b.ToTable("criteria", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Evidences.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("EvidenceTypeTemplateId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("NumericValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReviewerNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("EvidenceTypeTemplateId");

                    b.HasIndex("ApplicationId", "CriterionId", "Status");

                    b.ToTable("evidences", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Evidences.EvidenceTypeTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AttachmentPolicyJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FieldSchemaJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code", "Version")
                        .IsUnique();

                    b.ToTable("evidence_type_templates", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Standards.StandardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("AwardType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid?>("PreviousVersionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviousVersionId");

                    b.HasIndex("AcademicYear", "Level", "AwardType", "Version")
                        .IsUnique();

                    b.ToTable("standard_sets", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Submissions.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApplicantSnapshotJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ApplicantUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ApplicationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedReviewerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrganizationUnitId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("RecommendedForNextLevel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewerGeneralNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid?>("SourceApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StandardSetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionDataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationCode")
                        .IsUnique();

                    b.HasIndex("SourceApplicationId");

                    b.HasIndex("StandardSetId");

                    b.HasIndex("CampaignId", "Status", "AssignedReviewerId");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Submissions.ReviewLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("EvidenceId")
                        .HasColumnType("char(36)");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "CreatedAt");

                    b.ToTable("review_logs", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AvatarPublicId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("SecurityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Users.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AddressType")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProvinceOrCity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("varchar(4096)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AddressType")
                        .IsUnique();

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("AdministrativeClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("PoliticalStatus")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UnionPosition")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("SV5T.Domain.Welcome.PortalContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type", "IsPublished", "PublishedAtUtc");

                    b.ToTable("portal_contents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f35db57-0986-4f25-8a30-75ba664d4e01"),
                            Icon = "sparkles",
                            IsFeatured = true,
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 8, 10, 1, 0, 0, 0, DateTimeKind.Utc),
                            Route = "/dashboard",
                            Source = 1,
                            Summary = "Hồ sơ, minh chứng và thông tin xét duyệt của bạn sẽ được quản lý tập trung tại đây.",
                            Title = "Chào mừng bạn đến với hệ thống Sinh viên 5 Tốt",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0f35db57-0986-4f25-8a30-75ba664d4e02"),
                            Icon = "bell",
                            IsFeatured = false,
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 8, 9, 8, 30, 0, 0, DateTimeKind.Utc),
                            Route = "/dashboard?view=evidence",
                            Source = 4,
                            Summary = "Sinh viên vui lòng kiểm tra thông tin cá nhân trước khi nộp minh chứng.",
                            Title = "Chuẩn bị mở đợt cập nhật hồ sơ học kỳ I",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0f35db57-0986-4f25-8a30-75ba664d4e03"),
                            Icon = "shield-check",
                            IsFeatured = false,
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 8, 8, 3, 15, 0, 0, DateTimeKind.Utc),
                            Route = "/dashboard",
                            Source = 1,
                            Summary = "Phiên đăng nhập và dữ liệu cá nhân được xác thực an toàn qua hệ thống.",
                            Title = "Tài khoản của bạn đã được bảo vệ",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0f35db57-0986-4f25-8a30-75ba664d4e04"),
                            Icon = "landmark",
                            IsFeatured = true,
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 8, 10, 0, 30, 0, 0, DateTimeKind.Utc),
                            Route = "/dashboard?news=university-activities-2026",
                            Source = 2,
                            Summary = "Nhà trường công bố kế hoạch hoạt động học thuật, hội nhập và tình nguyện dành cho sinh viên.",
                            Title = "Khởi động chuỗi hoạt động sinh viên năm học 2026–2027",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("0f35db57-0986-4f25-8a30-75ba664d4e05"),
                            Icon = "graduation-cap",
                            IsFeatured = false,
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 8, 9, 2, 0, 0, 0, DateTimeKind.Utc),
                            Route = "/dashboard?news=faculty-innovation-week",
                            Source = 3,
                            Summary = "Nhiều workshop chuyên môn và hoạt động kết nối doanh nghiệp sẽ diễn ra trong tháng 8.",
                            Title = "Khoa phát động tuần lễ học tập và đổi mới sáng tạo",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("0f35db57-0986-4f25-8a30-75ba664d4e06"),
                            Icon = "heart-handshake",
                            IsFeatured = false,
                            IsPublished = true,
                            PublishedAtUtc = new DateTime(2026, 8, 8, 7, 0, 0, 0, DateTimeKind.Utc),
                            Route = "/dashboard?news=volunteer-recruitment",
                            Source = 4,
                            Summary = "Đăng ký tham gia đội hình hỗ trợ nhập học và tích lũy hoạt động cho tiêu chí tình nguyện tốt.",
                            Title = "Đoàn Thanh niên tuyển tình nguyện viên hỗ trợ tân sinh viên",
                            Type = 2
                        });
                });

            modelBuilder.Entity("SV5T.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("SV5T.Domain.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SV5T.Domain.Campaigns.Campaign", b =>
                {
                    b.HasOne("SV5T.Domain.Campaigns.Campaign", "PrerequisiteCampaign")
                        .WithMany("DependentCampaigns")
                        .HasForeignKey("PrerequisiteCampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SV5T.Domain.Standards.StandardSet", "StandardSet")
                        .WithMany()
                        .HasForeignKey("StandardSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrerequisiteCampaign");

                    b.Navigation("StandardSet");
                });

            modelBuilder.Entity("SV5T.Domain.Criteria.Criterion", b =>
                {
                    b.HasOne("SV5T.Domain.Criteria.Criterion", "ParentCriterion")
                        .WithMany("Children")
                        .HasForeignKey("ParentCriterionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SV5T.Domain.Standards.StandardSet", "StandardSet")
                        .WithMany("Criteria")
                        .HasForeignKey("StandardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCriterion");

                    b.Navigation("StandardSet");
                });

            modelBuilder.Entity("SV5T.Domain.Evidences.Evidence", b =>
                {
                    b.HasOne("SV5T.Domain.Submissions.Application", "Application")
                        .WithMany("Evidences")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SV5T.Domain.Criteria.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SV5T.Domain.Evidences.EvidenceTypeTemplate", "EvidenceTypeTemplate")
                        .WithMany()
                        .HasForeignKey("EvidenceTypeTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Criterion");

                    b.Navigation("EvidenceTypeTemplate");
                });

            modelBuilder.Entity("SV5T.Domain.Standards.StandardSet", b =>
                {
                    b.HasOne("SV5T.Domain.Standards.StandardSet", "PreviousVersion")
                        .WithMany("LaterVersions")
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("SV5T.Domain.Submissions.Application", b =>
                {
                    b.HasOne("SV5T.Domain.Campaigns.Campaign", "Campaign")
                        .WithMany("Applications")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SV5T.Domain.Submissions.Application", "SourceApplication")
                        .WithMany("NextLevelApplications")
                        .HasForeignKey("SourceApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SV5T.Domain.Standards.StandardSet", "StandardSet")
                        .WithMany()
                        .HasForeignKey("StandardSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("SourceApplication");

                    b.Navigation("StandardSet");
                });

            modelBuilder.Entity("SV5T.Domain.Submissions.ReviewLog", b =>
                {
                    b.HasOne("SV5T.Domain.Submissions.Application", "Application")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("SV5T.Domain.Users.UserAddress", b =>
                {
                    b.HasOne("SV5T.Domain.Users.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SV5T.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("SV5T.Domain.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("SV5T.Domain.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SV5T.Domain.Campaigns.Campaign", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("DependentCampaigns");
                });

            modelBuilder.Entity("SV5T.Domain.Criteria.Criterion", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("SV5T.Domain.Standards.StandardSet", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("LaterVersions");
                });

            modelBuilder.Entity("SV5T.Domain.Submissions.Application", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("NextLevelApplications");

                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("SV5T.Domain.Users.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
